---
version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    container_name: appsDB
    restart: always
    ports:
     - '6603:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
    - '8080:80'
    environment:
      PMA_HOST: db