---
#Creating users and giving them sudo roles
- hosts: all
  become: true
  connection: "local"
  vars:
    users:
      - Alexandre
      - Melanie
      - Axel
  tasks:
    - name: Create user accounts and add users to groups
      user:
        name: "{{ item }}"
        groups: "sudo,www-data"
      with_items: "{{ users }}"

#Install git
- hosts: all
  become: true
  tasks:
    - name: Install git
      apt:
        name: git
        state: latest
        update_cache: yes

#Install docker via geerlingguy ansible galaxy templates
- hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

- hosts: all
  become: true
  vars:
    nodejs_npm_global_packages:
      - name: jslint
  roles:
    - geerlingguy.nodejs
