---
- hosts: "localhost"
  connection: "local"
  vars:
    users:
      - Alexandre
      - Melanie
      - Axel
  tasks:
    - name: Create user accounts and add users to groups
      user:
        name: "{{ item }}"
        groups: "sudo,www-data"
      with_items: "{{ users }}"
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

